# Generated by Django 6.0.2 on 2026-02-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('student_class', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('address', models.TextField()),
                ('parents_phone', models.CharField(max_length=15)),
                ('exam_marks', models.IntegerField(default=0)),
                ('attendance', models.IntegerField(default=0)),
                ('total_fees', models.IntegerField(default=0)),
                ('fees_paid', models.IntegerField(default=0)),
                ('fees_pending', models.IntegerField(default=0)),
            ],
        ),
    ]
