# Generated by Django 5.2.10 on 2026-03-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_age_alter_staff_id_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
